### ISSUE TITLE
(Bug) A Pokemon dont has Pre / Evolutions

### ISSUE THREAD

**Issue by SilverPhoenixx** [Rafacasari/cobbledex#5]
Hey,

im currently checking out your 1.0.20 (Tests)

Problem:
Right click Pokemon with Pokedex
Selecting: Evolution
Result: Seeing their evolution

But the pokedex gets stuck on the last found pokemon.

Like: Find a pokemon -> Select one from before -> the latest found pokemon shows up

![Screenshot_6](https://github.com/Rafacasari/cobbledex/assets/38799048/3220b52e-fd0a-42c6-9f1c-ac8fd44b484d)
![Screenshot_7](https://github.com/Rafacasari/cobbledex/assets/38799048/89bbaf94-2ef4-41af-ab13-4d945d7d8f7f)

**Comment by Rafacasari** [comment]
Seems fixed in [v1.0.22](https://github.com/Rafacasari/cobbledex/releases/tag/v1.0.22).
Thanks for the report.
