### ISSUE TITLE
(Feature) Showing every possible type of pokemon 

### ISSUE THREAD

**Issue by SilverPhoenixx** [Rafacasari/cobbledex#6]
Hey

currently if you open the pokedex with "Forms" only "Alolan" or something like that gets loaded.
But not different tree types like torterra has like cherry, spruce, jungle etc.

Shiny dont get showed as well.

![Screenshot_8](https://github.com/Rafacasari/cobbledex/assets/38799048/3aca13ba-06a5-49b6-b916-3f2d864276bc)
![Screenshot_9](https://github.com/Rafacasari/cobbledex/assets/38799048/09964774-64f0-449b-9c8d-e99bd0b6c224)
![Screenshot_10](https://github.com/Rafacasari/cobbledex/assets/38799048/1d40d37f-79b0-4c71-987d-e10b18277041)

**Comment by SilverPhoenixx** [comment]
Edit

Current Version: 1.0.21
Interesting is, if i right click now Grotle, i see in Evolutions all the "Forms" of Torterra but not in Torterras Forms Category

Idk if i understand forms wrong

**Comment by Rafacasari** [comment]
Good point. I'll take a look on this.

**Comment by Rafacasari** [comment]
Seems it's not really an issue with Cobbledex, Cobblemon doesn't consider Torterra variant as a form
In a (near) future I do want to make quick buttons to see shiny/gender/color variants, but for now I'm closing this
