### ISSUE TITLE
(Feature) Search bar needed

### ISSUE THREAD

**Issue by LyquidQrystal** [Rafacasari/cobbledex#8]
Thank you for making this mod. I like the Where to find list. It frees me from finding the spawning condition of some pokemon. However, I noticed that there is not a search bar in the cobbledex, which means I have to find the pokemon first before knowing where it lives. Adding a search bar might make this mod more immersive.
Besides, will there be any support for the pokemon added by the datapacks? I use datapacks from modrinth but copying the spawing condition is quite annoying. 
Thank you agian for you and your mod.
(This Roaring Moon was added by marcustars' HiddenMons)
![2024-06-25_12 53 38](https://github.com/Rafacasari/cobbledex/assets/62202086/f8e88f50-4257-4f7f-b86c-39499abefcd8)

**Comment by Rafacasari** [comment]
You can use **/cobbledex [pokemon]** as a search.
About the spawning for datapacks, I'm pretty sure some people had tested and seems to work, I'll double check on Discord.

**Comment by Rafacasari** [comment]
Added in v1.0.27. Coming soon to Modrinth/CurseForge
