### ISSUE TITLE
(Feature) Show if a pokemon has already been Seen, caught, or not in the Pokedex.

### ISSUE THREAD

**Issue by tosagger** [Rafacasari/cobbledex#9]
I love how frequent you are updating the mod and it seems you really are working at it. I would love if it shows if a pokemon has already been caught or seen before, or if unseen. Would be amazing and just a little feature that'd be nice!

**Comment by Rafacasari** [comment]
It's already been worked on. Should be available to test in some hours or tomorrow

**Comment by Rafacasari** [comment]
Already available on test builds. Will be available on Modrinth/CurseForge really soon (when all tests is done)
